# Generated by Django 5.0.3 on 2026-05-27 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CircuitBreakerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        choices=[("ALDEAMO", "Aldeamo"), ("TWILIO", "Twilio")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CLOSED", "Closed — Normal operation"),
                            ("OPEN", "Open — Provider failing, requests rejected"),
                            ("HALF_OPEN", "Half-Open — Testing recovery"),
                        ],
                        default="CLOSED",
                        max_length=10,
                    ),
                ),
                ("failure_count", models.IntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circuit Breaker State",
                "verbose_name_plural": "Circuit Breaker States",
            },
        ),
        migrations.CreateModel(
            name="OtpRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "provider_used",
                    models.CharField(
                        blank=True,
                        choices=[("ALDEAMO", "Aldeamo"), ("TWILIO", "Twilio")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "OTP Request",
                "verbose_name_plural": "OTP Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("projected", models.BooleanField(default=False)),
                ("projected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Outbox Event",
                "verbose_name_plural": "Outbox Events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["projected", "created_at"],
                        name="otp_outboxe_project_6792f8_idx",
                    )
                ],
            },
        ),
    ]
